name: Send a Tweet

on:
  workflow_dispatch:

env:
  TWEET_PATH: out

### Requires V1 API and elevated access
#      - uses: lazy-actions/tweet-action@1.0.1
#        with:
#          message: ${{ env.TWEET }}
#          oauth_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#          oauth_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


jobs:
  update:
    strategy:
      matrix:
        test: ["a", "b"]

    name: Create tweets for ${{ matrix.type }}
    runs-on: ubuntu-22.04
    steps:
      - name: Create messages
        run: |
          mkdir -p "${TWEET_PATH}"
          echo "Hallo \n${{ matrix.test }} 1" | jq --raw-input --slurp -c . > ${TWEET_PATH}/${{ matrix.test }}-1.tweet
          echo "Holla \n${{ matrix.test }} 2" | jq --raw-input --slurp -c . > ${TWEET_PATH}/${{ matrix.test }}-2.tweet
      - name: Upload Tweets
        uses: actions/upload-artifact@v3
        with:
          name: tweets
          path: ${{ env.TWEET_PATH }}/
          if-no-files-found: ignore

  create-tweet-matrix:
    runs-on: ubuntu-22.04
    needs: update
    steps:
      - name: Download Tweets
        uses: actions/download-artifact@v3
        with:
          name: tweets
          path: ${{ env.TWEET_PATH }}/
      - name: Create Matrix
        id: create-matrix
        run: |
          # create empty dummy file, so cat does not fail
          mkdir -p "${TWEET_PATH}"
          echo > "${TWEET_PATH}/dummy.tweet"
          TWEETS=$(cat "${TWEET_PATH}"/*.tweet | jq --slurp -c .)
          echo "::set-output name=tweets::${TWEETS}"
    outputs:
      tweets: ${{ steps.create-matrix.outputs.tweets }}

  tweet:
    runs-on: ubuntu-22.04
    needs: create-tweet-matrix
    strategy:
      fail-fast: false
      matrix:
        tweet: ${{ fromJson(needs.create-tweet-matrix.outputs.tweets) }}
    steps:
      - name: Tweet
        run: echo '${{ matrix.tweet }}'
#      - uses: Eomm/why-don-t-you-tweet@v1
#        env:
#          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
#        with:
#          tweet-message: ${{ matrix.tweet }}
