name: Send a Tweet

on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "TWEET<<EOTWEET"  >> $GITHUB_ENV
          echo "Hi, this is a"   >> $GITHUB_ENV
          echo "multiline tweet" >> $GITHUB_ENV
          echo "EOTWEET"         >> $GITHUB_ENV
      - uses: Eomm/why-don-t-you-tweet@v1
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          tweet-message: ${{ env.TWEET }}

### Requires V1 API and elevated access
#      - uses: lazy-actions/tweet-action@1.0.1
#        with:
#          message: ${{ env.TWEET }}
#          oauth_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#          oauth_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
